### PR TITLE
Fix demand and action

### LINKED ISSUE #51: Climate action processing too aggressive?
Climate action is read from the unit reliably then processed to obtain the reported value.

If the compressor demand is 0, the action is demoted to idle. I'm not sure this is correct. Sometimes, despite the setpoint differing from the current temperature, the inside unit coil is hot/cold enough that the fan is the limiting factor in the system. The inside air handler is capable of heating/cooling for some time before needing to top up its heating/cooling capacity from the outdoor unit. When subtly maintaining a room's temperature, it appears as if the unit is idle when it's actually heating/cooling.

This is purely an interpretation choice. Some users might want to know the unit is doing something to heat/cool the space. Others might prefer knowing when the unit is placing demand on the compressor. Both choices are recoverable from the raw data from the unit: setpoint temperature differing from actual or the compressor demand sensor. This choice affects only the climate component reported action.

Sound off in the comments: would you prefer the unit report the local action or continue reporting the overall wider system action?

### PR DESCRIPTION
**Pull request by asund**
- Don't truncate demand value
- Use unit state to correct action
- Fix protocol debugging logic
- Organize some local state and naming

Closes #51

### CODE REVIEW

File: components/daikin_s21/s21.cpp [hunk 1]
```diff
@@ -561,7 +574,7 @@ void DaikinS21::handle_env_outside_temperature(const std::span<const uint8_t> pa
 }
 
 void DaikinS21::handle_env_indoor_frequency_command_signal(const std::span<const uint8_t> payload) {
-  this->demand = bytes_to_num(payload) / 10;  // Demand, 0-15
+  this->demand = bytes_to_num(payload);  // Demand, 0-15
```
Comment (asund) [inline components/daikin_s21/s21.cpp:577]: Fix regression
